import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { sanityClient, urlFor } from "../lib/sanity";
import styles from "../styles/Home.module.css";

const reciprQuery = `*[_type=="recipe"]{
  _id,
  name,
  slug,
  mainImage
}`;

export default function Home({ recipes }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jones&rsquo;s Kitchem</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to Jones&rsquo;s Kitchen 🍍</h1>

      <ul className="recipe-list">
        {recipes?.length > 0 &&
          recipes.map((recipe) => (
            <li key={recipe._id} className="recipe-card">
              <Link href={`/recipes/${recipe.slug.current}`}>
                <a>
                  <Image
                    src={urlFor(recipe.mainImage).url()}
                    layout="responsive"
                    alt={recipe.name}
                    width={300}
                    height={300}
                    className="recipe-image"
                  />
                  <span>{recipe.name}</span>
                </a>
              </Link>
            </li>
          ))}
      </ul>
    </div>
  );
}

export async function getStaticProps() {
  const recipes = await sanityClient.fetch(reciprQuery);
  return { props: { recipes } };
}
